name: Deploy HAPI FHIR Server, Load IG and Test Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ig_repo:
        description: 'IG Repository (e.g., hl7au/au-fhir-ig)'
        required: false
        default: 'hl7au/au-fhir-ig'
      test_data_repo:
        description: 'Test Data Repository (e.g., hl7au/au-fhir-test-data)'
        required: false
        default: 'hl7au/au-fhir-test-data'
      uploadfig_config:
        description: 'Path to UploadFIG config file (relative to repo root)'
        required: false
        default: 'uploadfig.json'
      ig_package_id:
        description: 'IG Package ID (e.g., hl7.fhir.au.core)'
        required: false
        default: 'hl7.fhir.au.core'
      ig_package_version:
        description: 'IG Package Version (e.g., 1.1.0-preview)'
        required: false
        default: '1.1.0-preview'
      hapi_server:
        description: 'path to local hapi server'
        required: false
        default: 'http://localhost:8080/fhir'
      terminology_server:
        description: 'the termininology server to hit to resolve ig references used by uploadfig'
        required: false
        default: 'https://api.healthterminologies.gov.au/integration/R4/fhir'

jobs:
  deploy_and_load:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    env:
      HAPI_VERSION: 6.5.1
      IG_REPO: ${{ github.event.inputs.ig_repo }}
      TEST_DATA_REPO: ${{ github.event.inputs.test_data_repo }}
      UPLOADFIG_CONFIG: ${{ github.event.inputs.uploadfig_config }}
      IG_PACKAGE_ID: ${{ github.event.inputs.ig_package_id }}
      IG_PACKAGE_VERSION: ${{ github.event.inputs.ig_package_version }}
      HAPI_SERVER: ${{ github.event.inputs.hapi_server }}
      TERM_SERVER: ${{ github.event.inputs.terminology_server }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Start HAPI FHIR Server
        run: |
          docker pull hapiproject/hapi:latest
          docker run -d -p 8080:8080 hapiproject/hapi:latest
          echo "Waiting for HAPI FHIR server to be ready..."

      - name: Wait for HAPI FHIR Server to start
        run: |
          until curl --silent --fail http://localhost:8080/fhir/metadata; do
            echo "Waiting..."
            sleep 10
          done
          echo "HAPI FHIR Server is running."

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Specify the .NET version you need
      
      - name: Install UploadFIG
        run: |
          dotnet tool install --global UploadFIG

      - name: Upload IG using UploadFIG
        run: |
          UploadFIG -pid ${{ env.IG_PACKAGE_ID }} -pv ${{ env.IG_PACKAGE_VERSION }} -d ${{ env.HAPI_SERVER }} --includeReferencedDependencies -reg ${{ env.TERM_SERVER }}

      - name: Clone Test Data
        run: |
          git clone https://github.com/${{ env.TEST_DATA_REPO }}.git test_data

      - name: Load Test Data
        run: |
          java -jar hapi-fhir-cli.jar upload-files -d test_data/au-fhir-test-data-set/ -s http://localhost:8080/fhir

      - name: Verify Test Data Loaded (Example, adjust as needed)
        run: |
          curl http://localhost:8080/fhir/Patient
